[tool.bumpversion]
current_version = "1.1.0-dev5"
parse = """(?x)
	(?P<major>\\d+)\\.
	(?P<minor>\\d+)\\.
	(?P<patch>\\d+)
	(?:-                    # dash separator for pre-release section
		(?P<pre_l>[a-zA-Z-]+)         # pre-release label
        (?P<pre_n>0|[1-9]\\d*)        # pre-release version number
    )?                                # pre-release section is optional
"""

serialize =[
	"{major}.{minor}.{patch}-{pre_l}{pre_n}",
	"{major}.{minor}.{patch}",
]

search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
ignore_missing_files = false
tag = false
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = false
commit = false
message = "Bump version: {current_version} → {new_version}"
commit_args = ""

[tool.bumpversion.parts.pre_l]
values = ["dev", "rc", "final"]
optional_value = "final"

[tool.bumpversion.parts.pre_n]
first_value = "1"

[[tool.bumpversion.files]]
filename = "pat/metadata.txt"
search   = 'version={current_version}'
replace  = 'version={new_version}'

[[tool.bumpversion.files]]
filename = "pat/metadata.txt"
search = "release_date = \\d{{4}}-\\d{{2}}-\\d{{2}} \\d{{2}}:\\d{{2}}:\\d{{2}}"
replace = "release_date = {now:%Y-%m-%d %H:%M:%S}"
regex = true