import os
print ("Current Directory =", os.getcwd())
print("cd pat")
os.chdir("pat")
print ("Current Directory =", os.getcwd())
print ("Contents of ", os.getcwd(), ":")
print(os.listdir("."))
print("Executing pb_tool compile")
os.system("pb_tool compile")
print("Skipping pb_tool deploy")
#os.system("pb_tool deploy -y")
print("Executing pb_tool zip")
os.system("pb_tool zip")
print ("Contents of ", os.getcwd(), ":")
print(os.listdir("."))
print ("Contents of ", os.path.join(os.getcwd(),"pat"), ":")
print(os.listdir("pat"))