name: Windows Build of QGis via 

on: push

env:
    PYPRECAG_BRANCH: master
    
jobs:
  build-windows:
    runs-on: windows-latest

    strategy:
      max-parallel: 5

    steps:
    
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Setup OSGeo4W environment
      id: setup-osgeo4w
      uses: echoix/setup-OSGeo4W@v0.2.0
      with:
        # Using line folding replacing newlines by a space, and striping the final newlines
        # See https://yaml-multiline.info/
        packages: >-
          qgis-ltr-full 
          cairo-devel
          freetype-devel
          gdal-devel
          geos-devel
          python3-core
          python3-tools
          python3-rasterio
          python3-fiona
          libjpeg-turbo-devel
          liblas-devel
          libpng-devel
          libpq-devel
          libtiff-devel
          netcdf-devel

    - name: Check directory
      run: |
        echo "Checking directories"
        dir
        dir C:\OSGeo4W
        dir C:\OSGeo4W\bin
        echo "Finished directory check."

    - name: Check osgeo
      run: |
          echo "Testing osgeo"
          C:\OSGeo4W\OSGeo4W.bat o-help
    
    - name: Check qgis-python
      run: |
          echo "Testing qgis-python"
          C:\OSGeo4W\OSGeo4W.bat python-qgis-ltr -m pip list

    - name: Install pbtools via qgis-python
      run: |
          echo "Testing qgis-python"
          C:\OSGeo4W\OSGeo4W.bat python-qgis-ltr -m pip install pbtools

    - name: Checkout of the $env:PYPRECAG_BRANCH branch of pyprecag"
      run: |
          echo "Checking out"
          git clone -b $env:PYPRECAG_BRANCH --single-branch --depth 1 https://github.com/CSIRO-Precision-Agriculture/pyprecag.git

    - name: Install the checked out pyprecag via qgis-python
      run: |
          echo "Do a pip install of the checked out version of pyprecag"
          C:\OSGeo4W\OSGeo4W.bat python-qgis-ltr -m pip install .\pyprecag
                  
    - name: Final check of qgis-python modules, i.e. does it contain pyprecag
      run: |
          echo "Testing qgis-python"
          C:\OSGeo4W\OSGeo4W.bat python-qgis-ltr -m pip list
   
      
