name: Windows Build of PAT QGis Plugin via OSGeo4W

on: push

env:
    PYPRECAG_BRANCH: master
    PYTHON_QGIS: C:\OSGeo4W\OSGeo4W.bat python-qgis-ltr
    
jobs:
  build-windows:
    runs-on: windows-latest

    strategy:
      max-parallel: 5

    steps:
    
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Setup OSGeo4W environment
      id: setup-osgeo4w
      uses: echoix/setup-OSGeo4W@v0.2.0
      with:
        # Using line folding replacing newlines by a space, and striping the final newlines
        # See https://yaml-multiline.info/
        packages: >-
          qgis-ltr-full 
          cairo-devel
          freetype-devel
          gdal-devel
          geos-devel
          python3-core
          python3-tools
          python3-rasterio
          python3-fiona
          libjpeg-turbo-devel
          liblas-devel
          libpng-devel
          libpq-devel
          libtiff-devel
          netcdf-devel

    - name: Check directory
      run: |
        echo "Checking directories"
        dir
        dir C:\OSGeo4W
        dir C:\OSGeo4W\bin
        echo "Finished directory check."

    - name: Check osgeo
      run: |
          echo "Testing osgeo"
          C:\OSGeo4W\OSGeo4W.bat o-help
    
    - name: Check qgis-python
      run: |
          echo "Testing qgis-python"
          C:\OSGeo4W\OSGeo4W.bat python-qgis-ltr -m pip list

    - name: Install pbtools via qgis-python
      run: |
          echo "Testing qgis-python"
          C:\OSGeo4W\OSGeo4W.bat python-qgis-ltr -m pip install pbtools
    
    - name: Install 7-Zip (for pbtool zip options)
      run: |
        echo "Download 7z.exe"
        curl https://www.7-zip.org/a/7zr.exe -o 7z.exe 
        echo "Place in OSGeo4W bin directory"
        cp 7z.exe C:\Osgeo4W\bin
        dir C:\Osgeo4W\bin
          

    - name: Checkout pyprecag from git repository"
      run: |
          echo "Checking out $env:PYPRECAG_BRANCH branch of pyprecag"
          git clone -b $env:PYPRECAG_BRANCH --single-branch --depth 1 https://github.com/CSIRO-Precision-Agriculture/pyprecag.git

    - name: Install the checked out pyprecag via qgis-python
      run: |
          echo "Do a pip install of the checked out version of pyprecag"
          C:\OSGeo4W\OSGeo4W.bat python-qgis-ltr -m pip install .\pyprecag
                  
    - name: Final check of qgis-python modules, i.e. does it contain pyprecag
      run: |
          echo "Testing qgis-python"
          C:\OSGeo4W\OSGeo4W.bat python-qgis-ltr -m pip list

    - name: Final check of qgis-python modules, i.e. does it contain pyprecag
      run: |
          echo "Testing qgis-python"
          C:\OSGeo4W\OSGeo4W.bat python-qgis-ltr -m pip list

    - name: Build and Package the PAT Qgis Plugin
      run: |
        echo "Invoking the pbt_ops.py python script. This will perform pbt compile, deploy and zip"
        C:\OSGeo4W\OSGeo4W.bat python-qgis-ltr .\pat\pbt_ops.py
        echo "Checking the zip build directory"
        dir .
        dir .\pat
        #dir .\pat\zip_build

    - name: Try something else
      run: |
        echo "Call OSGeo4W.bat to setup env"
        C:\OSGeo4W\OSGeo4W.bat
        "call Call OSGeo4W.bat pb_tool"
        C:\OSGeo4W\OSGeo4W.bat pb_tool

      
