name: Windows Build of latest QGis from scratch

on: push

env:
    PYPRECAG_BRANCH: master
    
jobs:
  build-windows:
    runs-on: windows-latest

    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Download  osgeo4w-setup installer from https://download.osgeo.org
      run: |
        echo "Downloading osgeo4w-setup.exe"
        curl https://download.osgeo.org/osgeo4w/v2/osgeo4w-setup.exe  -o osgeo4w-setup.exe 
        dir 
        
    - name: Install Latest version of QGIS via osgeo4w-setup.exe 
      run: |
        echo "Installing QGIS"
        .\osgeo4w-setup.exe  -q -b -A -k -n -s http://download.osgeo.org/osgeo4w/v2 -P python3-geopandas -P python3-rasterio
        echo "Finished install"
        dir C:\OSGeo4W
        echo "Done"
