name: Windows Build of QGis from scratch

on: workflow_dispatch

env:
    MNBV1: 42
    MNBV2: Myfile.txt
    #PYPRECAG_BRANCH: mnbMerge2Maint
    PYPRECAG_BRANCH: master
    QGIS_VER: '3.36.3'
    QGIS_MSI:  'https://qgis.org/downloads/QGIS-OSGeo4W-3.36.3-1.msi'
    QGIS_BIN: 'C:\Program Files\QGIS 3.36.3\bin'
    OSGEO4W_BAT: 'C:\Program Files\QGIS 3.36.3\OSGeo4W.bat' 
    PROG_FILES_DIR: 'C:\Program Files'
    BAT_FILE: 'OSGeo4W.bat'
    BAT_PATH: '${env:PROG_FILES_DIR}\${env:BAT_FILE}'
    OSGEO4WBAT:  '${env:PROG_FILES_DIR}\${env:BAT_FILE}'
    
jobs:
  build-windows:
    runs-on: windows-latest

    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        
    - name: Install QGIS
      run: |
        env
        echo "Trying Again 4.0 series"
        echo "MNBV1 is $env:MNBV1 and MNBV2 is $env:MNBV2"
        echo "GITHUB_ACTOR is $env:GITHUB_ACTOR"
        echo "Downloading OSGeo4W msi installer in $env:RUNNER_TEMP eg $env:RUNNER_TEMP\osgeo.msi"
        dir "C:\Program Files"
        #curl  https://qgis.org/downloads/QGIS-OSGeo4W-3.36.3-1.msi -o  D:\a\PAT_QGIS_Plugin\PAT_QGIS_Plugin\QGIS-OSGeo4W-3.36.3-1.msi 
        echo "Installing QGIS"
        #msiexec /i https://qgis.org/downloads/QGIS-OSGeo4W-3.36.3-1.msi /qn 
        echo "Use startProcess"
        start-Process msiexec -ArgumentList "/i https://qgis.org/downloads/QGIS-OSGeo4W-3.36.3-2.msi /qn " -Wait
        echo "Installing Osgeo4W Geopandas"
        & "C:\Program Files\QGIS 3.36.3\bin\osgeo4w-setup.exe" -q -b -A -k -n -s http://download.osgeo.org/osgeo4w/v2 -P python3-geopandas -P python3-rasterio
        echo "Uninstalling fiona"
        & 'C:\Program Files\QGIS 3.36.3\OSGeo4W.bat' python-qgis -m pip uninstall fiona --yes
        echo "Reinstalling fiona"
        & 'C:\Program Files\QGIS 3.36.3\OSGeo4W.bat' python-qgis -m pip install fiona
        dir "C:\Program Files"      
        
    - name: Install 7-Zip 
      run: |
        echo "Download 7z.exe"
        curl https://www.7-zip.org/a/7zr.exe -o 7z.exe 
        echo "Place in QGIS bin directory"
        cp 7z.exe "C:\Program Files\QGIS 3.36.3\bin"
        dir "C:\Program Files\QGIS 3.36.3\bin"

        
    - name: Check QGIS Installation
      run: |
        echo "Check The Program Files"
        dir "C:\Program Files"

        
    - name: Lint with flake8
      run: |
        echo "Activate the conda base environment"
        C:\Miniconda\condabin\conda.bat activate base
        echo "Install flake (for lint checking of python code)"
        C:\Miniconda\condabin\conda.bat install flake8
        # Syntax check the python code.
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide        
        C:\Miniconda\condabin\conda.bat run python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Installing pyprecag
      run: |
        # Check the base environment
        # Check the base environment
        echo "Looking for C:\Program Files\Qgis*-*"
        dir "C:\Program Files\QGIS*"
        dir "C:\Program Files\QGIS 3.36.3"
        echo "Attempt to list all the python packages available in the Qgis enviroment"
        echo "Check OSGeo4w.bat commands:"
        & 'C:\Program Files\QGIS 3.36.3\OSGeo4W.bat' o-help
        echo "Check python-qgis packages:"
        & 'C:\Program Files\QGIS 3.36.3\OSGeo4W.bat' python-qgis -m pip list
        echo "Install pb_tool package:"
        & 'C:\Program Files\QGIS 3.36.3\OSGeo4W.bat' python-qgis -m pip install pb_tool
        echo "Install pyprecag package:"
        ##### Example of installing from pypi
        ####& 'C:\Program Files\QGIS 3.36.3\OSGeo4W.bat' setup -q -k -r -A -s https://download.osgeo.org/osgeo4w/v2/ -P proj
        ####& 'C:\Program Files\QGIS 3.36.3\OSGeo4W.bat' python-qgis -m pip install pyprecag
        ### Example of checking out a specific branch version of pyprecag and installing via pip
        echo "Do a git checkout of the $env:PYPRECAG_BRANCH branch of pyprecag"
        git clone -b $env:PYPRECAG_BRANCH --single-branch --depth 1 https://github.com/CSIRO-Precision-Agriculture/pyprecag.git
        echo "Do a pip install of the checked out version of pyprecag"
        & 'C:\Program Files\QGIS 3.36.3\OSGeo4W.bat' python-qgis -m pip install .\pyprecag
        #echo "Try a pip re install of fiona"
        #& 'C:\Program Files\QGIS 3.36.3\OSGeo4W.bat' python-qgis -m pip install fiona
        ##echo "Do a git checkout of the latest main branch of pyprecag"
        ##git clone -b master --single-branch --depth 1 https://github.com/CSIRO-Precision-Agriculture/pyprecag.git
        ##echo "Do a pip install of the checked out version of pyprecag"
        ##& 'C:\Program Files\QGIS 3.36.3\OSGeo4W.bat' python-qgis -m pip install .\pyprecag
        
        echo "Check python-qgis packages after pip installs:"
        & 'C:\Program Files\QGIS 3.36.3\OSGeo4W.bat' python-qgis -m pip list        

        
    - name: Build and Package the PAT Qgis Plugin
      run: |
        echo "Invoking the pbt_ops.py python script. This will perform pbt compile, deploy and zip"
        & $env:OSGEO4W_BAT python-qgis .\pat\pbt_ops.py
        echo "Checking the zip build directory"
        dir .\pat\zip_build

    - name: Executing Unit Tests similar to the Geocoding Nominatum Testing
      run: |
        dir .\pat\tests
        echo "Perform unit tests"
        #& 'C:\Program Files\QGIS 3.36.3\OSGeo4W.bat' python-qgis -m unittest discover -s .\pat\tests -p test_*
        echo "Just try a single test"
        & 'C:\Program Files\QGIS 3.36.3\OSGeo4W.bat' python-qgis -m unittest .\pat\tests\test_cleanTrim.py

        
    - name: Upload pat.zip file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact.zip
        path: .\pat\zip_build\pat.zip
